#ifndef CVVERSIONING_H
#define CVVERSIONING_H
#include <opencv2/core/core.hpp>
#if  CV_MAJOR_VERSION >= 4
#include <opencv2/imgproc.hpp>

#define CV_BGR2GRAY cv::COLOR_BGR2GRAY
#define CV_GRAY2BGR cv::COLOR_GRAY2BGR
#define CV_FONT_HERSHEY_COMPLEX cv::FONT_HERSHEY_COMPLEX
#define CV_INTER_NN cv::INTER_LINEAR
#define CV_CAP_PROP_EXPOSURE cv::CAP_PROP_EXPOSURE
#define CV_CAP_PROP_PAN cv::CAP_PROP_PAN
#define CV_CAP_PROP_TILT cv::CAP_PROP_TILT
#define CV_CAP_PROP_ZOOM cv::CAP_PROP_ZOOM
#define CV_CAP_PROP_SETTINGS cv::CAP_PROP_SETTINGS
#define CV_CAP_PROP_FRAME_WIDTH cv::CAP_PROP_FRAME_WIDTH
#define CV_CAP_PROP_FRAME_HEIGHT cv::CAP_PROP_FRAME_HEIGHT
#define CV_CAP_PROP_FRAME_COUNT cv::CAP_PROP_FRAME_COUNT
#define CV_CAP_PROP_FPS cv::CAP_PROP_FPS
#define CV_CAP_PROP_POS_FRAMES cv::CAP_PROP_POS_FRAMES
#define CV_CAP_PROP_FORMAT cv::CAP_PROP_FORMAT
#define CV_CAP_PROP_FOURCC cv::CAP_PROP_FOURCC
#define CV_CAP_PROP_MODE cv::CAP_PROP_MODE
#define CV_CAP_PROP_BRIGHTNESS cv::CAP_PROP_BRIGHTNESS
#define CV_CAP_PROP_CONTRAST cv::CAP_PROP_CONTRAST
#define CV_CAP_PROP_SATURATION  cv::CAP_PROP_SATURATION
#define CV_CAP_PROP_GAIN cv::CAP_PROP_GAIN
#define CV_CAP_PROP_CONVERT_RGB cv::CAP_PROP_CONVERT_RGB
#define CV_CAP_PROP_WHITE_BALANCE_BLUE_U cv::CAP_PROP_WHITE_BALANCE_BLUE_U
#define CV_CAP_PROP_WHITE_BALANCE_RED_V cv::CAP_PROP_WHITE_BALANCE_RED_V
#endif



#endif // CVVERSIONING_H
